# Import the necessary stuff

In [1]:
import os
os.sys.path
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp


In [2]:
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities
mp_face_mesh = mp.solutions.face_mesh
mp_drawing_styles = mp.solutions.drawing_styles

In [6]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results


In [4]:
def draw_landmarks(image, results): #Holistic Use This One
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION) # Draw face connections

In [5]:
def draw_styled_landmarks(image, results):  #Holistic Use This One
    # Draw face connections
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
                             mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             ) 

## This Code for detecting Irish (still not work)

# Tester 

## another TEster

In [3]:
# For webcam input:
drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)
cap = cv2.VideoCapture('videos/ss_003_2.mp4')

with mp_face_mesh.FaceMesh(max_num_faces=1, refine_landmarks=True, min_detection_confidence=0.5, min_tracking_confidence=0.5) as face_mesh:
    while True:
        #cap.isOpened():
        success, image = cap.read()

        # Flip the image horizontally for a selfie-view display.
        image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)

        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False

        # Detect the face landmarks
        results = face_mesh.process(image)
        
        # To improve performance
        image.flags.writeable = True
        
        # Convert back to the BGR color space
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        
        if results.multi_face_landmarks:
            for face_landmarks in results.multi_face_landmarks:
                mp_drawing.draw_landmarks(
                    image=image,
                    landmark_list=face_landmarks,
                    connections=mp_face_mesh.FACEMESH_TESSELATION,
                    landmark_drawing_spec=None,
                    connection_drawing_spec=mp_drawing_styles
                   .get_default_face_mesh_tesselation_style())
#                mp_drawing.draw_landmarks(
#                    image=image,
#                    landmark_list=face_landmarks,
#                    connections=mp_face_mesh.FACEMESH_CONTOURS,
#                    landmark_drawing_spec=None,
#                    connection_drawing_spec=mp_drawing_styles
#                    .get_default_face_mesh_contours_style())
                mp_drawing.draw_landmarks(
                    image=image,
                    landmark_list=face_landmarks,
                    connections=mp_face_mesh.FACEMESH_IRISES,
                    landmark_drawing_spec=None,
                    connection_drawing_spec=mp_drawing_styles
                    .get_default_face_mesh_iris_connections_style())
                
        # Display the image
        cv2.imshow('MediaPipe FaceMesh', image)


        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()

In [6]:
# tester code for collect array

ress = np. array(results.multi_face_landmarks)
resss = ress[0].landmark
faces = np.array([[res.x, res.y, res.z, res.visibility] for res in resss])
faces[1]
#face = np.array([[res.x, res.y, res.z] for res in results.multi_face_landmarks])


array([ 0.50480503,  0.44191268, -0.06115483,  0.        ])

In [ ]:
'''
export const MESH_ANNOTATIONS: {[key: string]: number[]} = {
  silhouette: [
    10,  338, 297, 332, 284, 251, 389, 356, 454, 323, 361, 288,
    397, 365, 379, 378, 400, 377, 152, 148, 176, 149, 150, 136,
    172, 58,  132, 93,  234, 127, 162, 21,  54,  103, 67,  109
  ],

  lipsUpperOuter: [61, 185, 40, 39, 37, 0, 267, 269, 270, 409, 291],
  lipsLowerOuter: [146, 91, 181, 84, 17, 314, 405, 321, 375, 291],
  lipsUpperInner: [78, 191, 80, 81, 82, 13, 312, 311, 310, 415, 308],
  lipsLowerInner: [78, 95, 88, 178, 87, 14, 317, 402, 318, 324, 308],

  rightEyeUpper0: [246, 161, 160, 159, 158, 157, 173],
  rightEyeLower0: [33, 7, 163, 144, 145, 153, 154, 155, 133],
  rightEyeUpper1: [247, 30, 29, 27, 28, 56, 190],
  rightEyeLower1: [130, 25, 110, 24, 23, 22, 26, 112, 243],
  rightEyeUpper2: [113, 225, 224, 223, 222, 221, 189],
  rightEyeLower2: [226, 31, 228, 229, 230, 231, 232, 233, 244],
  rightEyeLower3: [143, 111, 117, 118, 119, 120, 121, 128, 245],

  rightEyebrowUpper: [156, 70, 63, 105, 66, 107, 55, 193],
  rightEyebrowLower: [35, 124, 46, 53, 52, 65],

  rightEyeIris: [473, 474, 475, 476, 477],

  leftEyeUpper0: [466, 388, 387, 386, 385, 384, 398],
  leftEyeLower0: [263, 249, 390, 373, 374, 380, 381, 382, 362],
  leftEyeUpper1: [467, 260, 259, 257, 258, 286, 414],
  leftEyeLower1: [359, 255, 339, 254, 253, 252, 256, 341, 463],
  leftEyeUpper2: [342, 445, 444, 443, 442, 441, 413],
  leftEyeLower2: [446, 261, 448, 449, 450, 451, 452, 453, 464],
  leftEyeLower3: [372, 340, 346, 347, 348, 349, 350, 357, 465],

  leftEyebrowUpper: [383, 300, 293, 334, 296, 336, 285, 417],
  leftEyebrowLower: [265, 353, 276, 283, 282, 295],

  leftEyeIris: [468, 469, 470, 471, 472],

  midwayBetweenEyes: [168],

  noseTip: [1],
  noseBottom: [2],
  noseRightCorner: [98],
  noseLeftCorner: [327],

  rightCheek: [205],
  leftCheek: [425]
link for picture https://github.com/google/mediapipe/blob/a908d668c730da128dfa8d9f6bd25d519d006692/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

478 * 3 = 1434 keypoints


kinsip
mother
daughter
son
father
'''


In [7]:
def extract_face_keypoints(results):
    face = np.array([[res.x, res.y, res.z] for res in np.array(results.multi_face_landmarks)[0].landmark]).flatten() if results.multi_face_landmarks else np.zeros(468*3)
    return np.concatenate([face])

In [8]:
DATA_PATH = os.path.join('videos')


In [9]:
 #input:===================================================================================
drawing_spec = mp_drawing.DrawingSpec(thickness=1, circle_radius=1)
cap = cv2.VideoCapture('videos/ss_003_2.mp4')
frame_length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

with mp_face_mesh.FaceMesh(max_num_faces=1, refine_landmarks=True, min_detection_confidence=0.5, min_tracking_confidence=0.5) as face_mesh:
    for frame_num in range(frame_length):
        #cap.isOpened():
        ret, image = cap.read()

        # Flip the image horizontally for a selfie-view display.
        image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)

        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False

        # Detect the face landmarks
        results = face_mesh.process(image)
        
        # To improve performance
        image.flags.writeable = True

        # Convert back to the BGR color space
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        if results.multi_face_landmarks:
            for face_landmarks in results.multi_face_landmarks:
                mp_drawing.draw_landmarks(
                    image=image,
                    landmark_list=face_landmarks,
                    connections=mp_face_mesh.FACEMESH_TESSELATION,
                    landmark_drawing_spec=None,
                    connection_drawing_spec=mp_drawing_styles
                   .get_default_face_mesh_tesselation_style())
#                mp_drawing.draw_landmarks(
#                    image=image,
#                    landmark_list=face_landmarks,
#                    connections=mp_face_mesh.FACEMESH_CONTOURS,
#                    landmark_drawing_spec=None,
#                    connection_drawing_spec=mp_drawing_styles
#                    .get_default_face_mesh_contours_style())
                mp_drawing.draw_landmarks(
                    image=image,
                    landmark_list=face_landmarks,
                    connections=mp_face_mesh.FACEMESH_IRISES,
                    landmark_drawing_spec=None,
                    connection_drawing_spec=mp_drawing_styles
                    .get_default_face_mesh_iris_connections_style())

        # Display the image
        if frame_num == 0:
            cv2.putText(image, 'STARTING COLLECTION', (120,200),
                        cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
            cv2.putText(image, 'Collecting frames num {} Video {}'.format(frame_num, 'test'), (70,50), 
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
            # Show to screen
            cv2.imshow('MediaPipe FaceMesh', image)
            cv2.waitKey(500)
        else:
            cv2.putText(image, 'Collecting frames num {} Video {} '.format(frame_num, 'test'), (15,12), 
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
            # Show to screen
            cv2.imshow('MediaPipe FaceMesh', image)
                
        keypoints = extract_face_keypoints(results)
        npy_path = os.path.join(DATA_PATH, "male", str(frame_num))
        np.save(npy_path, keypoints)


        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

In [14]:
loaderr = np.load('videos/male/2.npy')
len(loaderr)   #lengt each array about 478 * 3 = 1434 

1434

In [21]:
loaderr[1]

0.5204129219055176

In [69]:
pose = []
for res in results.face_landmarks.landmark:
    test = np.array([res.x, res.y, res.z, res.visibility])
    pose.append(test)

In [73]:
results.face_landmarks

landmark {
  x: 0.50233567
  y: 0.51591986
  z: -0.03988601
}
landmark {
  x: 0.4993719
  y: 0.45072165
  z: -0.059901316
}
landmark {
  x: 0.500818
  y: 0.4783108
  z: -0.03688244
}
landmark {
  x: 0.48935306
  y: 0.3940802
  z: -0.038633432
}
landmark {
  x: 0.49886385
  y: 0.42952392
  z: -0.061577894
}
landmark {
  x: 0.49853304
  y: 0.40629947
  z: -0.054817654
}
landmark {
  x: 0.49832588
  y: 0.35787618
  z: -0.01774664
}
landmark {
  x: 0.42366898
  y: 0.38238806
  z: 0.02536705
}
landmark {
  x: 0.49815995
  y: 0.31872106
  z: -0.0045352466
}
landmark {
  x: 0.49785677
  y: 0.29279995
  z: -0.0029372505
}
landmark {
  x: 0.49640754
  y: 0.20795272
  z: 0.02079334
}
landmark {
  x: 0.5026939
  y: 0.525418
  z: -0.03917902
}
landmark {
  x: 0.50301534
  y: 0.53311574
  z: -0.03643866
}
landmark {
  x: 0.50317115
  y: 0.5362059
  z: -0.032465797
}
landmark {
  x: 0.5035749
  y: 0.54026896
  z: -0.034501918
}
landmark {
  x: 0.50371134
  y: 0.5460668
  z: -0.037491553
}
landmark {

In [13]:
pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.face_landmarks.landmark]).flatten()

In [15]:
pose.shape

(1872,)

In [17]:
len(pose)

1872

In [19]:
cap = cv2.VideoCapture('videos/ss_003_2.mp4')
length = int(cap. get(cv2. CAP_PROP_FRAME_COUNT))
print( length )

403


In [25]:
pose = []
for res in results.face_landmarks.landmark:
    test = np.array([res.x, res.y, res.z, res.visibility])
    pose.append(test)

In [27]:
face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)

In [28]:
face

array([ 0.49968019,  0.51672047, -0.04087141, ...,  0.58278197,
        0.35196349,  0.02644201])

# Code for extracting Keypoints Holistic

In [7]:
def extract_keypoints(results):
    face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    return np.concatenate([face])

In [12]:
result_test = extract_keypoints(results)

In [8]:
results.face_landmarks.landmark

[x: 0.5015904
y: 0.51601934
z: -0.041270148
, x: 0.49864456
y: 0.4483261
z: -0.061391473
, x: 0.5000911
y: 0.47690964
z: -0.038090575
, x: 0.4888955
y: 0.3921456
z: -0.039473403
, x: 0.49822763
y: 0.4271028
z: -0.06300032
, x: 0.4980578
y: 0.404114
z: -0.055999894
, x: 0.49821594
y: 0.35619968
z: -0.018135108
, x: 0.42282096
y: 0.3809062
z: 0.025818285
, x: 0.49822405
y: 0.31737638
z: -0.0046191816
, x: 0.4979757
y: 0.29155803
z: -0.0029091176
, x: 0.49684927
y: 0.20659257
z: 0.02154626
, x: 0.5019568
y: 0.5259449
z: -0.040641114
, x: 0.50227505
y: 0.53415936
z: -0.037941918
, x: 0.50243
y: 0.5375856
z: -0.03395492
, x: 0.5029069
y: 0.5521576
z: -0.034145195
, x: 0.5030116
y: 0.5588368
z: -0.03717091
, x: 0.50311965
y: 0.5685358
z: -0.041317053
, x: 0.50335133
y: 0.5816816
z: -0.042244006
, x: 0.503729
y: 0.60887486
z: -0.036266338
, x: 0.4990733
y: 0.4616354
z: -0.057028487
, x: 0.48871922
y: 0.4647611
z: -0.043111444
, x: 0.39066032
y: 0.32937428
z: 0.08770164
, x: 0.45282403
y: 0.38

In [234]:
mp_face_mesh.FACEMESH_IRISES

frozenset({(469, 470),
           (470, 471),
           (471, 472),
           (472, 469),
           (474, 475),
           (475, 476),
           (476, 477),
           (477, 474)})

In [6]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('videos') 

# Actions that we try to detect
actions = np.array([ 'male', 'female'])

# Thirty videos worth of data
no_sequences = 48

# Videos are 403 frames in length
sequence_length = frame_length

# Folder start
start_folder = 30

NameError: name 'frame_length' is not defined

## this code for make folder to collect data automatically

In [16]:

    for sequence in range(1,no_sequences+1):
        try: 
            os.makedirs(os.path.join(DATA_PATH, 'female', str(sequence)))
        except:
            pass

## this code for collect data that loop through frames

In [13]:
cap = cv2.VideoCapture('videos/Male_002.mp4')
frame_length = int(cap. get(cv2. CAP_PROP_FRAME_COUNT))
print( frame_length )
keypoint = np.empty(shape=(0, 1404)) #change to 0 , 0 if want to collect flatten   array
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    
    
    
    # Loop through video length aka SEQUENCE LENGTH = NUMBER OF FRAME
    for frame_num in range(frame_length):
        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)

        # Draw landmarks
        draw_styled_landmarks(image, results)
                
        # Apply wait logic
        if frame_num == 0: 
            cv2.putText(image, 'STARTING COLLECTION', (120,200),
                        cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
            cv2.putText(image, 'Collecting frames num {} Video {}'.format(frame_num, 'test'), (15,12), 
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
            # Show to screen
            cv2.imshow('OpenCV Feed', image)
            cv2.waitKey(500)
        else:
            cv2.putText(image, 'Collecting frames num {} Video {} '.format(frame_num, 'test'), (15,12), 
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
            # Show to screen
            cv2.imshow('OpenCV Feed', image)
                
        # NEW Export keypoints
        keypoints = extract_keypoints(results)
        #keypoint = np.append(keypoint, keypoints.reshape((-1, 1404)), axis=0)
        npy_path = os.path.join(DATA_PATH, "male", str(frame_num))
        np.save(npy_path, keypoints)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
                    
    cap.release()
    cv2.destroyAllWindows()
    

725


In [181]:
loaderr = np.load('videos/male/2.npy')

In [182]:
len(loaderr)

1404

In [183]:
loaderr.shape

(1404,)

In [166]:
s1 = loaderr.flatten()


In [167]:
s1.shape

(565812,)

In [174]:
print(os.path.join(DATA_PATH, "male", str(frame_num)))

videos\male\402


In [ ]:
cap = cv2.VideoCapture('videos/ss_003_2.mp4')
frame_length = int(cap. get(cv2. CAP_PROP_FRAME_COUNT))
print( frame_length )
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(start_folder, start_folder+no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, holistic)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # NEW Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(500)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

In [ ]:
result_test.shape

In [168]:
step_n = 10
steps = np.empty(shape=(0, 1))
for n in range(step_n-1):
    step = np.random.choice([1, 2, 3], size=(1,1))
    print(steps)
    steps = np.append(steps, step, axis=0)
    #something will be checked after each n
    np.save('0', steps)


[]
[[2.]]
[[2.]
 [3.]]
[[2.]
 [3.]
 [2.]]
[[2.]
 [3.]
 [2.]
 [1.]]
[[2.]
 [3.]
 [2.]
 [1.]
 [2.]]
[[2.]
 [3.]
 [2.]
 [1.]
 [2.]
 [1.]]
[[2.]
 [3.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]]
[[2.]
 [3.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [3.]]


In [5]:
cap = cv2.VideoCapture('videos/ss_003_2.mp4')
while(cap.isOpened()):
  ret, frame = cap.read()
  gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
  cv2.imshow('frame',gray)
  if cv2.waitKey(1) & 0xFF == ord('q'):
    break

cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
